'use strict';

module.exports = [
    {
        price: 1,
        max_buy_count: 10,
        _id: 1,
        app_name: '魔法哈奇',
        create_date: '2017-11-27 15:37:15',
        is_on_sale: 1,
        additional_field: [
            {
                desc: '以给不属于自己的角色ID充值',
                required: 1,
                name: 'user_nid',
                displayName: '角色ID',
            },
        ],
        goods_id: 1,
        app_goods_id: 984,
        subject: '魔法哈奇',
        default_buy_count: 10,
        body:
            '您正在进行《魔法哈奇》的魔豆充值，魔豆可在《魔法哈奇》中购买商城物品与服务',
        exchange_rate: 10,
        min_buy_count: 10,
    },
    {
        price: 1,
        max_buy_count: 1000,
        _id: 2,
        app_name: '魔法哈奇2',
        create_date: '2017-11-27 15:38:57',
        is_on_sale: 1,
        additional_field: [
            {
                desc: '可以给不属于自己的角色ID充值',
                required: 1,
                name: 'user_nid',
                displayName: '角色ID',
            },
        ],
        goods_id: 2,
        app_goods_id: 984,
        subject: '魔法哈奇2',
        default_buy_count: 10,
        body:
            '您正在进行《魔法哈奇2》的魔豆充值，魔豆可在《魔法哈奇2》中购买商城物品与服务。',
        exchange_rate: 10,
        min_buy_count: 100,
    },
    {
        price: 1,
        max_buy_count: 1000,
        _id: 3,
        app_name: 'KEEPWORK',
        create_date: '2017-11-27 15:43:34',
        is_on_sale: 1,
        additional_field: [
            {
                desc: 'vip开通订单号',
                required: 1,
                name: 'vip_order_no',
                displayName: 'vip开通订单号',
            },
        ],
        goods_id: 3,
        app_goods_id: 1,
        subject: 'KEEPWORK会员',
        default_buy_count: 10,
        body: '为KEEPWORK开通VIP',
        exchange_rate: 1,
        min_buy_count: 100,
    },
    {
        price: 1,
        max_buy_count: 1000,
        _id: 4,
        app_name: '教育平台',
        create_date: '2017-11-27 15:46:55',
        is_on_sale: 1,
        additional_field: [
            {
                desc: '订单号',
                required: 1,
                name: 'order_no',
                displayName: '订单号',
            },
        ],
        goods_id: 4,
        app_goods_id: 1,
        subject: '道峰学堂教学服务',
        default_buy_count: 10,
        body: '道峰学堂，人人都可以在线学习，人人都可以成为导师',
        exchange_rate: 1,
        min_buy_count: 100,
    },
    {
        max_buy_count: 1000,
        subject: 'vip',
        _id: 5,
        exchange_rate: 1,
        create_date: '2018-05-14 10:49:53',
        additional_field: [
            {
                desc: '订单号',
                required: 1,
                name: 'order_no',
                displayName: '订单号',
            },
        ],
        price: 1,
        min_buy_count: 100,
        app_name: 'lessons',
        is_on_sale: 1,
        default_buy_count: 10,
        body: 'Everyone Likes Animations, Learn Programming with Them.',
        app_goods_id: 1,
        goods_id: 5,
    },
    {
        max_buy_count: 1000,
        app_goods_id: 2,
        _id: 6,
        app_name: 'KEEPWORK',
        create_date: '2018-07-06 18:54:24',
        subject: 'Paracraft线下培训班',
        price: 1,
        goods_id: 6,
        exchange_rate: 1,
        additional_field: [],
        default_buy_count: 1000,
        body: 'Paracraft线下培训班',
        is_on_sale: 1,
        min_buy_count: 1000,
    },
    {
        max_buy_count: 100,
        _id: 7,
        goods_id: 7,
        create_date: '2018-08-08 11:16:37',
        exchange_rate: 1,
        min_buy_count: 1,
        subject: '香安帅锅',
        app_goods_id: 1,
        is_on_sale: 1,
        default_buy_count: 1,
        additional_field: [
            {
                desc: 'vip_order_no',
                required: 1,
                name: 'vip_order_no',
                displayName: 'vip_order_no',
            },
        ],
        app_name: '香安',
        price: 1,
    },
    {
        price: 1,
        min_buy_count: 100,
        _id: 8,
        is_on_sale: 1,
        create_date: '2018-09-20 19:47:05',
        exchange_rate: 1,
        max_buy_count: 10000,
        goods_id: 8,
        additional_field: [],
        app_name: 'LessonVIP',
        default_buy_count: 10,
        body: 'Lessons 尊享VIP会员',
        app_goods_id: 1,
        subject: 'Lessons包年服务',
    },
    {
        max_buy_count: 1000,
        price: 1,
        app_goods_id: 967,
        thumbnail:
            'https://api.keepwork.com/storage/v0/siteFiles/856/raw#FhZvBPJHRq9TSLGmVy0OOzD87vBc.png',
        _id: 9,
        bean: 10,
        create_date: '2018-09-29 19:15:54',
        subject: '能量石碎片（1天）',
        min_buy_count: 1,
        goods_id: 9,
        additional_field: [],
        is_on_sale: 1,
        default_buy_count: 1,
        body: '',
        exchange_rate: 1,
        app_name: '魔法哈奇',
    },
    {
        exchange_rate: 1,
        max_buy_count: 1000,
        app_goods_id: 17316,
        thumbnail:
            'https://api.keepwork.com/storage/v0/siteFiles/855/raw#FrcOff3UetSvrS9lK0Qi-c4nQL5I.png',
        _id: 10,
        bean: 20,
        create_date: '2018-09-29 19:16:48',
        subject: '丰厚仙豆口袋（绑定）',
        min_buy_count: 10,
        goods_id: 10,
        additional_field: [],
        is_on_sale: 1,
        default_buy_count: 1,
        body: '',
        app_name: '魔法哈奇',
        price: 1,
    },
    {
        exchange_rate: 1,
        max_buy_count: 1000,
        app_goods_id: 17484,
        thumbnail:
            'https://api.keepwork.com/storage/v0/siteFiles/854/raw#Fsa30gsXVi8fINIyDejxtQV9vY9c.png',
        _id: 11,
        bean: 60,
        create_date: '2018-09-29 19:17:34',
        subject: '激战魔珠',
        min_buy_count: 10,
        goods_id: 11,
        additional_field: [],
        is_on_sale: 1,
        default_buy_count: 1,
        body: '',
        app_name: '魔法哈奇',
        price: 1,
    },
    {
        goods_id: 12,
        max_buy_count: 1000,
        app_name: '魔法哈奇',
        thumbnail:
            'https://api.keepwork.com/storage/v0/siteFiles/852/raw#FlU2Ve6nhlgLInBbIuZIciMyuBX3.png',
        _id: 12,
        bean: 70,
        create_date: '2018-09-29 19:18:24',
        app_goods_id: 16150,
        subject: '尤诺的雪地车（7天）',
        min_buy_count: 10,
        is_on_sale: 1,
        additional_field: [],
        default_buy_count: 1,
        body: '',
        exchange_rate: 1,
        price: 10,
    },
    {
        goods_id: 13,
        max_buy_count: 1000,
        app_name: '魔法哈奇',
        thumbnail:
            'https://api.keepwork.com/storage/v0/siteFiles/853/raw#Fuz7rEnBVLdY9KBtvOpZP4qEZ9F6.png',
        _id: 13,
        bean: 70,
        create_date: '2018-09-29 19:19:12',
        app_goods_id: 17389,
        subject: '捕鱼达人套餐',
        min_buy_count: 1,
        is_on_sale: 1,
        additional_field: [],
        default_buy_count: 1,
        body: '',
        exchange_rate: 1,
        price: 10,
    },
];
